/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-05-05 00:18:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Models.User;

public final class find_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html\" charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("<title>Find</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<a href=\"index.jsp\"> <input type=\"button\" value=\"Home\"\n");
      out.write("\t\tclass=\"button\"></a>\n");
      out.write("\n");
      out.write("\t<form action=\"find.jsp\" method=\"post\">\n");
      out.write("\t\t<select name=\"option\">\n");
      out.write("\t\t\t<option value=\"u_id\">ID</option>\n");
      out.write("\t\t\t<option value=\"username\">Username</option>\n");
      out.write("\t\t\t<option value=\"email\">Email</option>\n");
      out.write("\t\t\t<option value=\"firstname\">Firstname</option>\n");
      out.write("\t\t\t<option value=\"lastname\">Lastname</option>\n");
      out.write("\t\t</select> <input type=\"search\" name=\"search\" class=\"input\"> <input\n");
      out.write("\t\t\ttype=\"submit\" value=\"Search\" class=\"button\">\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t");

		String option = request.getParameter("option");
		String search = request.getParameter("search");
	
      out.write('\n');
      out.write('\n');
      out.write('	');

		request.setAttribute("option", option);
		request.setAttribute("search", search);
		RequestDispatcher dispatcher = request.getRequestDispatcher("./search");
		dispatcher.include(request, response);
	
      out.write('\n');
      out.write('\n');
      out.write('	');

		ArrayList<User> users = null;
		users = (ArrayList<User>) request.getAttribute("users");
	
      out.write('\n');
      out.write('\n');
      out.write('	');

		if (users != null) {
	
      out.write("\n");
      out.write("\t<table class=\"tablea\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>ID</td>\n");
      out.write("\t\t\t<td>Username</td>\n");
      out.write("\t\t\t<td>Email</td>\n");
      out.write("\t\t\t<td>Firstname</td>\n");
      out.write("\t\t\t<td>Lastname</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\t\t");

			for (int i = 0; i < users.size(); i++) {
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>");
      out.print(users.get(i).getId());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(users.get(i).getUsername());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(users.get(i).getEmail());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(users.get(i).getFirstname());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(users.get(i).getLastname());
      out.write("</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t");

			}
		
      out.write("\n");
      out.write("\t</table>\n");
      out.write("\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
